### ISSUE TITLE
compilation with node 0.11/0.12 breaks

### ISSUE THREAD

**Issue by alice0meta** [FrontierPsychiatrist/node-spotify#81]
note: This issue was opened before node 0.12 was released.

This is worth fixing quickly, because the same work will need to be done for 0.12, which is coming out soon.

Here's a pastebin of the error messages I got: http://pastebin.com/TJ0zkkPT

**Comment by FrontierPsychiatrist** [comment]
Ha, I knew this would come up some day. A rather large transition is necessary as 0.11 breaks the interface for native addons. At the same time it won't work anymore for 0.10 so I can only start this in a branch.

**Comment by drsounds** [comment]
I too have this issue, need to resolve this because I work with a Spotify related project in node-webkit.
http://github.com/drsounds/bungalow.git

**Comment by FrontierPsychiatrist** [comment]
Ok. @alice0meta, can you give me a quick hint on how to set up a environment where 0.12 is used? Then I can try to make a branch that compiles there.

**Comment by alice0meta** [comment]
(0.12 isn't released yet - you mean 0.11?)

http://strongloop.com/strongblog/node-js-v0-12-c-apis-breaking/ looks like the relevant guide on the api changes

I found https://github.com/creationix/nvm adequate for managing multiple node versions - you can just run the install script and then say things like "nvm install 0.11" or "nvm use 0.11".

**Comment by FrontierPsychiatrist** [comment]
I just saw node.js 0.12 is now stable so this needs to be addressed quickly. I'll see what I can do, but it will need a complete rewrite of the node classes...

**Comment by bendi** [comment]
Do you plan to use [nan](https://www.npmjs.com/package/nan)?

**Comment by FrontierPsychiatrist** [comment]
Thanks for the heads up, @bendi , didn't know that existed. I'll try it out!

**Comment by FrontierPsychiatrist** [comment]
Started working on this, see branch issue-81. I hope when all compiles it will also work...

**Comment by FrontierPsychiatrist** [comment]
I'm able to login and access the sessionUser with 0.12 in the branch issue-81 again. If someone in this issue could try that out, too I would be grateful.

Thanks again @bendi , nan has been a real help.

I think currently 0.10 compilation is broken, haven't setup nvm yet. I use some libuv functions that are not encapsulated in nan and I need to put in custom preprocessor switches.

Lot's of getV8Object() need to be replaced with createInstance() before everything works again...

**Comment by bendi** [comment]
I'll give it a try today - I also have io.js 1.0.5-nightly (arm :))

**Comment by FrontierPsychiatrist** [comment]
Cool :+1: Actually it wasn't that many replacements - I replaced all of the getV8Object calls and now the basic browsing should pretty much work.

Searching and album/artist browsing is broke, though.

**Comment by FrontierPsychiatrist** [comment]
And to make it more fun, lldb refuses to work with an interactive node.js 0.12 prompt.

**Comment by bendi** [comment]
0.10.28 build failed :( [logs attached](http://maracuya-jukebox.com/labs/node-spotify/build-0.10.28-20150222.log)

**Comment by FrontierPsychiatrist** [comment]
Yes, that's exactly the lines I need to do different for 0.10 and nan can't do that for me (it's more about V8 compatibility, not libuv). I'll try to fix that soon, it shouldn't be too hard.

**Comment by FrontierPsychiatrist** [comment]
@bendi can you try again? I added a version check to NodeAudioHandler and SessionCallbacks.

**Comment by bendi** [comment]
Still got some errors :( [log](http://maracuya-jukebox.com/labs/node-spotify/build-0.10.28-20150223.log)

**Comment by FrontierPsychiatrist** [comment]
Yeah I'm an idiot (and also thought I could do it without compiling it myself). Can you try again now?

**Comment by bendi** [comment]
Ok created pull request - fixed here and there and it works on 0.10.28 :)

**Comment by FrontierPsychiatrist** [comment]
Album/Artist browsing works again.

Checking playlist(container) callbacks next, and node.js audio. But I think this is nearly finished - it looks very good.

**Comment by FrontierPsychiatrist** [comment]
Fixed in 0.7.1, pushed to npm.

Couldn't try out io.js yet but it works in node..js 0.10 and 0.12.

Since I'm planning to switch to node-pre-gyp for binary distribution I won't provide binaries for this version. I also need to implement some automated build system since the number of binaries for 3 node.js version, 3 cpu types and 2 compile flags is a whopping 18...

**Comment by drsounds** [comment]
Could you implement windows support for streaming music (Using Win32 Audio
APIs or DirectX)?

Best regards,
Alexander Forselius (Dr. Sounds)
Musician, and programmer.
http://dr-sounds.com

Github
<http://t.signaleuna.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1q0Mw-W8r4PxK7fsJrMW3N1zH656dR01f5JhpKW02?t=http%3A%2F%2Fwww.github.com%2Fkrikelin&si=5411275823644672&pi=7d74fbf1-c95f-4dbc-a2d5-f9f0b0bec88a>
Twitter
<http://t.signaleuna.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1q0Mw-W8r4PxK7fsJrMW3N1zH656dR01f5JhpKW02?t=http%3A%2F%2Fwww.twitter.com%2Fdrsounds&si=5411275823644672&pi=7d74fbf1-c95f-4dbc-a2d5-f9f0b0bec88a>
Spotify
<http://t.signaleuna.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1q0Mw-W8r4PxK7fsJrMW3N1zH656dR01f5JhpKW02?t=http%3A%2F%2Fopen.spotify.com%2Fartist%2F2FOROU2Fdxew72QmueWSUy&si=5411275823644672&pi=7d74fbf1-c95f-4dbc-a2d5-f9f0b0bec88a>
<http://t.signaleuna.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1q0Mw-W8r4PxK7fsJrMW3N1zH656dR01f5JhpKW02?t=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3Dpjdujamrcds&si=5411275823644672&pi=7d74fbf1-c95f-4dbc-a2d5-f9f0b0bec88a>
LinkedIn
<http://t.signaleuna.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1q0Mw-W8r4PxK7fsJrMW3N1zH656dR01f5JhpKW02?t=http%3A%2F%2Fse.linkedin.com%2Fpub%2Falexander-forselius%2F13%2Fb11%2F500%2F&si=5411275823644672&pi=7d74fbf1-c95f-4dbc-a2d5-f9f0b0bec88a>


2015-03-03 21:01 GMT+01:00 Moritz Schulze <notifications@github.com>:

**Comment by FrontierPsychiatrist** [comment]
I wish I could - but neither do I know how to handle audio in Windows nor have I setup a node.js native addon development environment in Windows. I haven't found a good tutorial so far :(

It's on my mind-roadmap for version 1.0 but I can't guarantee anything.

**Comment by drsounds** [comment]
I understand.



Best regards,
Alexander Forselius (Dr. Sounds)
Musician, and programmer.
http://dr-sounds.com

Github
<http://t.signaleuna.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1q0Mw-W8r4PxK7fsJrMW3N1zH656dR01f5JhpKW02?t=http%3A%2F%2Fwww.github.com%2Fkrikelin&si=5411275823644672&pi=080cb6d6-c505-4ff5-eca8-c0c9637db022>
Twitter
<http://t.signaleuna.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1q0Mw-W8r4PxK7fsJrMW3N1zH656dR01f5JhpKW02?t=http%3A%2F%2Fwww.twitter.com%2Fdrsounds&si=5411275823644672&pi=080cb6d6-c505-4ff5-eca8-c0c9637db022>
Spotify
<http://t.signaleuna.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1q0Mw-W8r4PxK7fsJrMW3N1zH656dR01f5JhpKW02?t=http%3A%2F%2Fopen.spotify.com%2Fartist%2F2FOROU2Fdxew72QmueWSUy&si=5411275823644672&pi=080cb6d6-c505-4ff5-eca8-c0c9637db022>
<http://t.signaleuna.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1q0Mw-W8r4PxK7fsJrMW3N1zH656dR01f5JhpKW02?t=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3Dpjdujamrcds&si=5411275823644672&pi=080cb6d6-c505-4ff5-eca8-c0c9637db022>
LinkedIn
<http://t.signaleuna.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1q0Mw-W8r4PxK7fsJrMW3N1zH656dR01f5JhpKW02?t=http%3A%2F%2Fse.linkedin.com%2Fpub%2Falexander-forselius%2F13%2Fb11%2F500%2F&si=5411275823644672&pi=080cb6d6-c505-4ff5-eca8-c0c9637db022>


2015-03-03 21:08 GMT+01:00 Moritz Schulze <notifications@github.com>:

**Comment by drsounds** [comment]
I read that Spotify has discountinued libspotify and is developing new
libraries and APIs that will replace it soon, so node-spotify will soon be
obsolute.

I used NodeSpotify for my project Bungalow, which is a clone of what
Spotify was in 2009 but with some new goodies such hashtag view, and I
constructed my nw-app by putting all node stuff in an internal node server
(on the client) and only have front end specific stuff in the JS/HTML, to
ease stuff. LibSpotify was a source of mess, and I really hope Spotify will
add full length streaming on their web api soon. If so, I can complete my
bungalow project, now I'm limbo since there is no full length streaming
available.

http://github.com/drsounds/bungalow

Best regards,
Alexander Forselius (Dr. Sounds)
Musician, and programmer.
http://dr-sounds.com

Github
<http://t.sidekickopen03.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1q0Mw-W8r4PxK7fsJrMW3N1zH656dR01f5JhpKW02?t=http%3A%2F%2Fwww.github.com%2Fkrikelin&si=5411275823644672&pi=6e2d1e03-c670-49af-a771-694bbe2ac44e>
Twitter
<http://t.sidekickopen03.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1q0Mw-W8r4PxK7fsJrMW3N1zH656dR01f5JhpKW02?t=http%3A%2F%2Fwww.twitter.com%2Fdrsounds&si=5411275823644672&pi=6e2d1e03-c670-49af-a771-694bbe2ac44e>
Spotify
<http://t.sidekickopen03.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1q0Mw-W8r4PxK7fsJrMW3N1zH656dR01f5JhpKW02?t=http%3A%2F%2Fopen.spotify.com%2Fartist%2F2FOROU2Fdxew72QmueWSUy&si=5411275823644672&pi=6e2d1e03-c670-49af-a771-694bbe2ac44e>
<http://t.sidekickopen03.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1q0Mw-W8r4PxK7fsJrMW3N1zH656dR01f5JhpKW02?t=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3Dpjdujamrcds&si=5411275823644672&pi=6e2d1e03-c670-49af-a771-694bbe2ac44e>
LinkedIn
<http://t.sidekickopen03.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1q0Mw-W8r4PxK7fsJrMW3N1zH656dR01f5JhpKW02?t=http%3A%2F%2Fse.linkedin.com%2Fpub%2Falexander-forselius%2F13%2Fb11%2F500%2F&si=5411275823644672&pi=6e2d1e03-c670-49af-a771-694bbe2ac44e>


2015-03-03 21:12 GMT+01:00 Alexander Forselius <drsounds@gmail.com>:
