### ISSUE TITLE
pause and stop too slow

### ISSUE THREAD

**Issue by JeremyPouyet** [FrontierPsychiatrist/node-spotify#86]
If I call spotify.player.pause() or spotify.player.stop(), the music stop or pause but only one second after the function call (Ubuntu 13.04 or raspberry pi 3.12).

Does this happen to anyone else ?

**Comment by FrontierPsychiatrist** [comment]
Do you use JavaScript or native audio?

In JavaScript audio it's probably the buffer, with native audio it shouldn't be one second.

**Comment by kashimsax** [comment]
I use native audio except if it's possible to use Javascript audio without calling spotify.useNodeJsAudio().

my code just call your functions : 

```
var spotify = require("./build/Release/spotify")({appkeyFile: 'path'});
Player.prototype = {
  pause: function() {
     spotify.player.pause();
  },
  stop: function() {
    spotify.player.stop();
  }
/* other functions */
};
```

By searching more, I have the same problem with libspotify in C.
I have modified the Spotify jukebox example program to integrate a `sp_session_player_play(g_sess, 0)`: 

```
/* 
** ...
** spotify C code in jukebox.c
*/
sp_session_player_load(g_sess, t);
sp_session_player_play(g_sess, 1);
/* Add my test line 123 */
sleep(2);
printf("will pause");
printf("pause return: %d\n", sp_session_player_play(g_sess, 0));
sleep(2);
printf("play again");
sp_session_player_play(g_sess, 1);
/* back to spotify C code */
```
This test display "will pause". Then, it immediately display "pause return: 0" (means no error) but the pause is still performed after one second. The next `sp_session_player_play(g_sess, 1)`, like in your JS code, is then immediate.

I have no idea about where the problem come from because I have no problem with the Spotify application.

Any idea ?
